pylint:
  image: python:3.6
  before_script:
    - python -m pip install pylint
  script:
    - pylint --jobs $(nproc) --exit-zero **/*.py
  cache:
    key: pylint--${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/pip

.base:
  image: $IMAGE
  services:
    - docker:dind
  before_script:
    - python -m pip install tox docker-compose
    - docker-compose -f test/docker-compose.yml up -d
  script:
    - tox -e $CI_JOB_NAME
  cache:
    key: pytest--${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.cache/pip
      - .tox

py36-salt2019-crypt-acme:
  extends: .base
  variables:
    IMAGE: python:3.6

py36-salt2018-crypt-acme:
  extends: .base
  variables:
    IMAGE: python:3.6

py36-salt2017-crypt-acme:
  extends: .base
  variables:
    IMAGE: python:3.6

py37-salt2019-crypt-acme:
  extends: .base
  variables:
    IMAGE: python:3.7

py37-salt2018-crypt-acme:
  extends: .base
  variables:
    IMAGE: python:3.7

ubuntu1804-py36-salt2017-crypt21-acme022:
  extends: .base
  variables:
    IMAGE: python:3.6

debian10-py37-salt2018-crypt26-acme031:
  extends: .base
  variables:
    IMAGE: python:3.7
