cache:
  key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
  paths:
    - $CI_PROJECT_DIR/.cache/pip
    - $CI_PROJECT_DIR/.tox

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

pylint:
  image: python:3.10
  before_script:
    - python -m pip install pylint
  script:
    - pylint --jobs $(nproc) --exit-zero **/*.py
