# Development and testing environment for salt-acme. The python tests
# run against these services, at the configured ports.
name: salt-acme

services:
  pebble:
    image: ghcr.io/letsencrypt/pebble:2.10.1@sha256:ddf230642b1a584f519f32e347de1b05a6e4c1f6c35c1863b33effeab5f78199
    command: -dnsserver 127.0.0.153:53
    environment:
      PEBBLE_AUTHZREUSE: 0
      PEBBLE_WFE_NONCEREJECT: 0
      PEBBLE_VA_NOSLEEP: ${PEBBLE_VA_NOSLEEP:-1}
    ports:
      - 127.0.0.1:14000:14000 # HTTPS ACME API
      - 127.0.0.1:15000:15000 # HTTPS Management API
      - 127.0.0.153:53:53/tcp # DNS
      - 127.0.0.153:53:53/udp # DNS
      - 127.0.0.1:5300:53/tcp # DNS
      - 127.0.0.1:5300:53/udp # DNS

  knot:
    image: cznic/knot:3.5@sha256:b9456df432136a15a8eb64191a8f22a5752e1e2180e24adecb9371ff759253c3
    command: knotd
    network_mode: service:pebble
    volumes:
      - ./test/fixtures/knot:/config:ro
